[package]
name = "adx"
version = "1.1.0"
authors = ["Harsh Shandilya <msfjarvis@gmail.com>"]
edition = "2018"
description = "Poll Google's Maven repository to fetch the latest versions of AndroidX packages"
repository = "https://github.com/msfjarvis/androidx-release-watcher"
keywords = ["maven", "androidx"]
readme = "README.md"
license-file = "LICENSE"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.0"
log = "0.4.8"
roxmltree = "0.9.1"
ureq = "0.11.3"
indicatif = "0.14.0"

[badges]
maintenance = { status = "actively-developed" }
