[package]
name = "androidx-release-watcher"
version = "0.1.0"
authors = ["Harsh Shandilya <msfjarvis@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.9.22"
clap = "2.33.0"
log = "0.4.8"
roxmltree = "0.7.3"
