[package]
name = "adx"
version = "0.2.0"
authors = ["Harsh Shandilya <msfjarvis@gmail.com>"]
edition = "2018"
description = "Poll Google's Maven repository to fetch the latest versions of AndroidX packages"
repository = "https://github.com/msfjarvis/androidx-release-watcher"
keywords = ["maven", "androidx"]
readme = "README.md"
license-file = "LICENSE"
# This has no purpose being on crates.io
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.9.22"
clap = "2.33.0"
log = "0.4.8"
roxmltree = "0.7.3"

[badges]
maintenance = { status = "actively-developed" }
