[package]
name = "adx"
version = "4.1.0"
authors = ["Harsh Shandilya <me@msfjarvis.dev>"]
edition = "2021"
license = "MIT/Apache-2.0"
description = "Poll Google's Maven repository to fetch the latest versions of AndroidX packages"
repository = "https://github.com/msfjarvis/androidx-release-watcher"
homepage = "https://github.com/msfjarvis/androidx-release-watcher"
keywords = ["maven", "androidx"]
readme = "../README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-std = { version = "1.10.0", features = ["attributes"] }
clap = { version = "3.0.0-beta.5", features = ["color"] }
color-eyre = { version = "0.5.11", default-features = false }
roxmltree = { version = "0.14.1", features = ["std"] }
semver = "1.0.4"
surf = { version = "2.3.1", default-features = false, features = ["h1-client-rustls"] }
thiserror = "1.0.30"
futures = "0.3.17"

[badges]
maintenance = { status = "actively-developed" }

[features]
measure-alloc = []
