[package]
name = "adx"
version = "4.3.1-alpha.0"
authors = ["Harsh Shandilya <me@msfjarvis.dev>"]
edition = "2021"
license = "MIT/Apache-2.0"
description = "Poll Google's Maven repository to fetch the latest versions of AndroidX packages"
repository = "https://github.com/msfjarvis/androidx-release-watcher"
homepage = "https://github.com/msfjarvis/androidx-release-watcher"
keywords = ["maven", "androidx"]
readme = "../README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.1.18", features = ["color", "derive"] }
color-eyre = { version = "0.6.1", default-features = false }
futures = "0.3.21"
reqwest = { version = "0.11.11", default-features = false, features = ["rustls-tls"] }
roxmltree = { version = "0.14.1", features = ["std"] }
semver = "1.0.10"
thiserror = "1.0.31"
tokio = { version = "1.19.2", features = ["macros", "rt-multi-thread"] }

[badges]
maintenance = { status = "actively-developed" }

[features]
measure-alloc = []
