[package]
name = "adx"
version = "4.3.4-alpha.0"
authors = ["Harsh Shandilya <me@msfjarvis.dev>"]
edition = "2021"
license = "MIT/Apache-2.0"
description = "Poll Google's Maven repository to fetch the latest versions of AndroidX packages"
repository = "https://github.com/msfjarvis/androidx-release-watcher"
homepage = "https://github.com/msfjarvis/androidx-release-watcher"
keywords = ["maven", "androidx"]
readme = "../README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.2.22", features = [ "color", "deprecated", "derive" ] }
color-eyre = { version = "0.6.2", default-features = false }
futures = "0.3.24"
reqwest = { version = "0.11.12", default-features = false, features = ["rustls-tls"] }
roxmltree = { version = "0.15.0", features = ["std"] }
semver = "1.0.14"
thiserror = "1.0.37"
tokio = { version = "1.21.2", features = ["macros", "rt-multi-thread"] }

[badges]
maintenance = { status = "actively-developed" }

[features]
measure-alloc = []
